# Generated by Django 4.2 on 2023-10-26 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0004_alter_trainingrecord_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='completed_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
