# Generated by Django 4.2 on 2023-11-09 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0005_alter_trainingrecord_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='completed_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
