# Generated by Django 4.2 on 2023-11-09 15:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0006_alter_trainingrecord_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='completed_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 12, 31))]),
        ),
    ]
