# Generated by Django 4.2 on 2023-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0007_alter_trainingrecord_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='completed_on',
            field=models.DateField(),
        ),
    ]
